### ISSUE TITLE
URL's ne fonctionnent pas

### ISSUE THREAD

**Issue by magnetic-eagle** [ArteGEIE/Presentation-Forum-PHP-2020#22]
Les URLs sur page 9 de la slide ne fonctionnent pas - est-ce que ça pourrait être fixé ? Il me les faut pour un petit programme qui alerte quand il y a de nouveaux vidéos d'émissions specifiques - merci en avance !

**Comment by zyhou** [comment]
Les différentes urls sont des exemples. L'API d'Arte n'est pas ouverte au public.

**Comment by magnetic-eagle** [comment]
ok, c'est bien dommage …
